# brix_home_page_locale:
#     path:     /{_locale}
#     defaults: { _controller: BrixCoreBundle:Page:loadHomePage }
#     requirements:
#         _locale: en|fr|de



# brix_home_page:
#     path:     /
#     defaults: { _controller: BrixCoreBundle:Page:loadHomePage }
#
#
#
brix_page:
    path:     /{url}
    defaults: { _controller: BrixCoreBundle:Page:loadPage, url: false }
    requirements:
        url: ".+"

        # _locale: en|fr|de
