parameters:
#    brix_brix.example.class: Brix\BrixBundle\Example

services:
    # brox_locale.locale_listener:
    #     class: Brix\CoreBundle\EventListener\LocaleListener
    #     arguments: ["%kernel.default_locale%"]
    #     tags:
    #         - { name: kernel.event_subscriber }
